trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-18.04

variables:
  - group: LearnDevops - Docker
  - name: configuration.dockerhub.connection
    value: cd-docker-hub

stages:
  - template: azure-pipelines/ci.yml
#- template: azure-pipelines/cd-dev.yml
#- template: azure-pipelines/cd-hml.yml
#- template: azure-pipelines/cd-prd.yml
