apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: learn-devops
spec:
  replicas: 4
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: iel182/estudo-docker:v20210314.2
          resources:
            limits:
              memory: "50Mi"
              cpu: "150m"
          ports:
            - containerPort: 80
