version: '3'

networks: 
  learndevops-netwrork:
    driver: 'bridge'

services:

  nginx:
    container_name: learn-devops-nginx
    restart: always
    build: 
      dockerfile: Dockerfile 
      context: ../nginx/
    depends_on: 
      - client    
    ports: 
      - '3050:80'
    networks:
      - learndevops-netwrork

  client:
    container_name: learn-devops-client
    build:
      context: ../src/LearnAzureDevOps
      dockerfile: Dockerfile
    volumes:    
      - ./client:/app
    depends_on: 
      - redis
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports: 
      - "5000:80"
    networks:
      - learndevops-netwrork

  redis:
    container_name: learn-devops-redis
    image: 'redis:latest'
