parameters:
  - name: cacheImages
    type: string
    default: mcr.microsoft.com/dotnet/sdk:5.0 mcr.microsoft.com/dotnet/aspnet:5.0

stages:
  - stage: ci
    variables:
      - group: LearnDevops - Docker
      - name: app.root
        value: $(System.DefaultWorkingDirectory)/src
      - name: app.imageName
        value: "iel182/estudo-docker"

      - app.docker.serviceconnection: $(DOCKER_HUB_SERVICE_CONNECTION)

    jobs:
      - job: Build

        steps:
          - checkout: self

          - task: Cache@2
            inputs:
              key: 'docker | "$(Agent.OS)" | cacheImages'
              path: $(Pipeline.Workspace)/docker
              cacheHitVar: DOCKER_CACHE_RESTORED
            displayName: Caching Docker imagee

          - script: |
              docker load < $(Pipeline.Workspace)/docker/aspnet5.tar
              docker load < $(Pipeline.Workspace)/docker/sdk5.tar
            condition: and(not(canceled()), eq(variables.DOCKER_CACHE_RESTORED, 'true'))
            displayName: docker load cache

          - script: |
              mkdir -p $(Pipeline.Workspace)/docker
              docker pull mcr.microsoft.com/dotnet/aspnet:5.0
              docker pull mcr.microsoft.com/dotnet/sdk:5.0
              docker save mcr.microsoft.com/dotnet/aspnet:5.0 > $(Pipeline.Workspace)/docker/aspnet5.tar
              docker save mcr.microsoft.com/dotnet/sdk:5.0 > $(Pipeline.Workspace)/docker/sdk5.tar
            condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_RESTORED, 'true')))
            displayName: docker image cache

          - task: UseDotNet@2
            displayName: dotnet install
            inputs:
              version: "5.0.x"
              packageType: runtime

          - task: DotNetCoreCLI@2
            displayName: dotnet build
            inputs:
              command: build
              projects: "$(app.root)/LearnAzureDevOps.sln"
              arguments: "--configuration Release"

          - task: DotNetCoreCLI@2
            displayName: dotnet test
            inputs:
              command: test
              projects: "$(app.root)/LearnAzureDevOps.sln"
              arguments: "--configuration Release --no-build /p:CollectCoverage=true /p:ConverletOutputFormat=opencover"
              publishTestResult: true

          - task: PublishCodeCoverageResults@1
            displayName: "publish code coverage report"
            inputs:
              codeCoverageTool: "Cobertura"
              summaryFileLocation: "$(Build.SourcesDirectory)/**/coverage.cobertura.xml"

          - task: DotNetCoreCLI@2
            displayName: dotnet publih
            inputs:
              command: publish
              projects: "$(app.root)/LearnAzureDevOps/LearnAzureDevOps.csproj"
              arguments: "--configuration Release --no-build --output $(System.Default.WorkingDirectory)/publish"
              publishWebProjects: true
              zipAfterPublish: false
              modifyOutputPath: false

          - task: Docker@2
            displayName: docker build image
            inputs:
              repository: $(app.imageName)
              command: build
              Dockerfile: $(app.root)/LearnAzureDevOps/Dockerfile
              tags: "v$(Build.BuildNumber)"

          - task: Docker@2
            displayName: docker push image
            inputs:
              command: push
              containerRegistry: ${app.docker.serviceconnection}
              repository: $(app.imageName)
              includeLatestTag: true
              tags: "v$(Build.BuildNumber)"
